# Generated by Django 3.1.7 on 2024-01-01 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=3000)),
                ('folder', models.CharField(max_length=20, null=True)),
                ('start_year', models.PositiveSmallIntegerField(default=None, null=True)),
                ('end_year', models.PositiveSmallIntegerField(default=None, null=True)),
                ('last_moved', models.DateField(default=None, null=True)),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.box')),
                ('category', models.ManyToManyField(null=True, to='catalogue.Category')),
            ],
        ),
    ]
